eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: http://vm-node-a.platform:8761/eureka/,http://vm-node-b.platform:8761/eureka/,http://vm-node-c.platform:8761/eureka/
  instance:
    hostname: ${spring.cloud.client.hostname}
    prefer-ip-address: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    lk.ijse.eca: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
