spring:
  mvc:
    problemdetails:
      enabled: true

  mongodb:
    uri: mongodb://root:bQEjW8hREhAWiKeZOnljPtx8w0JNQD16NYoYOdwvxJ-9Xwkr@f4f78138-332c-4fa3-8840-e98ab81de839.asia-southeast1.firestore.goog:443/eca-final-project-mongodb-vm?loadBalanced=true&tls=true&authMechanism=SCRAM-SHA-256&retryWrites=false
server:
  port: 0

eureka:
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
