spring:
  mvc:
    problemdetails:
      enabled: true

  mongodb:
    uri: mongodb://root:74AGt0PAzA9U8ZPuRtL0rcRJYR9tvrHkZFbacHMpWZQqzWKA@ee69ae43-c8f9-4355-a51a-5e5390c57e0a.asia-southeast1.firestore.goog:443/db-capstone?loadBalanced=true&tls=true&authMechanism=SCRAM-SHA-256&retryWrites=false

server:
  port: 0

eureka:
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
