spring:
  mvc:
    problemdetails:
      enabled: true

  mongodb:
    uri: mongodb://root:yrJ8NKKEiBoxKuRWcUwBM1RIIMCDlEX3XHXUySez7vdlOGIy@871235da-5428-4c0a-b6c9-c2a688ec20d0.asia-east2.firestore.goog:443/vm-eca-lm-final-project-mongodb?loadBalanced=true&tls=true&authMechanism=SCRAM-SHA-256&retryWrites=false

server:
  port: 0

eureka:
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
