spring:
  mvc:
    problemdetails:
      enabled: true

  mongodb:
    uri: mongodb://eca-lm-project-service-account:gNmXRm90nVN-WuBR1Bc4I15dp2kruvXeFcISTB1ruDuQaupp@17177b43-9dc2-43fd-8b75-69e3490c49fd.asia-east2.firestore.goog:443/eca-lm-project-mongodb-vm?loadBalanced=true&tls=true&authMechanism=SCRAM-SHA-256&retryWrites=false
server:
  port: 0

eureka:
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
