spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: book-service
              uri: lb://BOOK-SERVICE
              predicates:
                - Path=/api/books/**

            - id: member-service
              uri: lb://MEMBER-SERVICE
              predicates:
                - Path=/api/members/**

            - id: file-service
              uri: lb://FILE-SERVICE
              predicates:
                - Path=/api/files/**

          default-filters:
            - PreserveHostHeader

          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: "*"
                allowed-methods: "*"
                allowed-headers: "*"

server:
  port: 8080
